### PR TITLE
Reorders heading styles

### LINKED ISSUE #48: Re-order H styles
Ok so now that we've got the site up, guidance from Rachel on accessibility best practices and a thorough digging around on my part as to how we're actually using text and H stylings in context, I think we need to revise the ordering of our text styles as follows:

**Page title** 
no change

**Page intro text**
The CSS for H2 should be used for a paragraph style intended only for the top of each page. Ideally this is some kind of pre-set block or style, but otherwise, this issue https://github.com/MutualAidNYC/wp-theme/issues/45 will solve this. 

Screen Shot 2020-05-13 at 7 41 42 PM

**h2**
What is currently h4 is what should become our h2. This is the H style we're using as headers of main content areas. One note: the default style should not have the yellow highlight as most of the time we it isn't used that way. 

font-size: 1.75em;
line-height: 1.4;
font-weight: 700;

Screen Shot 2020-05-13 at 7 42 09 PM

**h3**
I think we just need to nix this lil guy. we're hardly using it and Rachel says it's throwing off the H ordering for screen readers because we're regularly skipping to H4. 

in that case, what is currently h5 should become h3. 

Screen Shot 2020-05-13 at 7 42 46 PM

**h4-h6**
keep moving everything else up 2 Hs

### PR DESCRIPTION
**Pull request by ChaosExAnima**
Fixes #48.

This PR does the following:
* Changes the order of header tag styles as per the issue.
* Removes unused font.

Front end:
Screen Shot 2020-05-15 at 10 09 02 PM

Back end:
Screen Shot 2020-05-15 at 10 09 02 PM

### CODE REVIEW

**Comment by ChaosExAnima** [comment]
@jffng - For the yellow background, you need to bold the text, as we can't have a spanning background color without some sort of nested element.

**Comment by jffng** [comment]
@ChaosExAnima Ahh right. I updated my comment with a screenshot that has an H2 with bold text. Still I think would be best for @mollieru to confirm that meets the guidance provided in #48.

**Comment by mollieru** [comment]
@ChaosExAnima @jffng thanks for the work here! This is super close, but the color styles need a touch of tweaking.

The text styling on [this page](https://mutualaid.nyc/for-groups-organizers/) show the H2 and H3 color/text treatments we're after:

- h2 = dark teal w no background by default
- h3 = purple w no background by default

**Comment by ChaosExAnima** [comment]
@mollieru - Do we want to be able to show that yellow background on h2s optionally, or never?

**Comment by mollieru** [comment]
optionally would be nice!

**Comment by ChaosExAnima** [comment]
Okay @jffng and @mollieru, here's the latest version with the color requests:
Screen Shot 2020-05-18 at 6 26 07 PM

Note that all you can still override all colors, and the yellow background on H2s is optional!

**Comment by jffng** [comment]
Looks good to me!

**Pull request merged**
