### PR TITLE
Adds sidebar template

### PR DESCRIPTION
**Pull request by ChaosExAnima**
Adds a sidebar template.

* This relies on #70.
* Sidebar width is capped at 300px.

#### Testing
1. Create or edit a page to use the sidebar template.
2. Use the Customizer to add a widget to the sidebar.
3. Change page width and watch sidebar response.

#### Screenshots
Screen Shot 2020-06-13 at 4 43 22 PM

### CODE REVIEW

**Comment by ChaosExAnima** [comment]
@jffng - What header are you referring to?

**Comment by ChaosExAnima** [comment]
@jffng - So I took a look at full/wide width alignment + sidebars, and it seems to be a core issue: https://github.com/WordPress/gutenberg/issues/4747

Right now, I see a few approaches we could take:

- Remove sidebars entirely and insert the ToC in a different spot.
- Disable full/wide support in the entire theme.
- Do some processing magic to check if a given post has wide blocks.
- Ask content folks to be careful with full/wide blocks and pages with sidebars.

I don't want to disable support, so that leaves the other three options. The lowest friction is the last option I feel and would be a decent interim until we have a better solution in place.

Open to suggestions here, though!

**Comment by jffng** [comment]
Could there be some sidebar template-specific CSS that targets align wide / full width blocks?

e.g. 

```css
@media (min-width: 1280px) {
  .template-sidebar .entry-content > .alignwide {
    max-width: calc(120rem - 300px);
    width: calc(120rem - 300px);
  }
}
@media (min-width: 700px) {
  .template-sidebar .entry-content > .alignwide {
     max-width: calc(100vw - 300px);
     width: calc(100vw - 300px);
  }
}
```

If this is too much cumbersome, then I think asking content folks to be mindful when using the sidebar template is a fine solution.

**Comment by ChaosExAnima** [comment]
@jffng - I pushed up a fix in 6633f57 where I flipped things so the width is constrained equally instead of trying to have a full-width page over the sidebar. It looks okay:
Screen Shot 2020-06-17 at 9 35 02 PM

Going to merge and we can create bugfixes from Q/A.

**Pull request merged**
